version: '3'

services:
  backend:
    build: .
    container_name: sofa_marketplace
    ports:
      - "8888:8000"
    environment:
      - SUPERUSER_PASSWORD=${SUPERUSER_PASSWORD}
    volumes:
      - .:/app
    working_dir: /app/source
    command: python manage.py runserver 0.0.0.0:8000