# Generated by Django 4.2.11 on 2024-05-19 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200914_1159'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='link',
        ),
        migrations.AlterField(
            model_name='profile',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
