# Generated by Django 4.2.11 on 2024-04-09 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='RoomCategory',
        ),
    ]
