# Generated by Django 4.2.11 on 2024-04-09 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='rooms',
            field=models.ManyToManyField(related_name='categories', to='webapp.room', verbose_name='Категории мебели'),
        ),
    ]
