# Generated by Django 4.2.11 on 2024-04-15 20:36

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='parent',
            field=smart_selects.db_fields.ChainedForeignKey(blank=True, chained_field='room', chained_model_field='room', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='webapp.category', verbose_name='Родительская категория'),
        ),
        migrations.AddField(
            model_name='category',
            name='room',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='webapp.room', verbose_name='Категории мебели'),
            preserve_default=False,
        ),
    ]
