# Generated by Django 4.2.11 on 2024-04-17 17:59

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='room',
            field=models.ForeignKey(default=10, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='webapp.room', verbose_name='Комната'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(default='1', max_length=50, verbose_name='Название категории мебели'),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.TextField(blank=True, max_length=2000, null=True, verbose_name='Описание')),
                ('amount', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Остаток')),
                ('price', models.DecimalField(decimal_places=2, max_digits=7, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Цена')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='product_pics', verbose_name='Изображение')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.category')),
                ('room', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='category', chained_model_field='room', on_delete=django.db.models.deletion.CASCADE, to='webapp.room')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
    ]
