# Generated by Django 4.2.11 on 2024-04-17 18:09

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_category_room_alter_category_name_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='room', chained_model_field='room', on_delete=django.db.models.deletion.CASCADE, to='webapp.category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='room',
            field=models.ForeignKey(default=10, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='webapp.room'),
        ),
    ]
