# Generated by Django 4.2.11 on 2024-04-17 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_alter_product_category_alter_product_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Название категории мебели'),
        ),
    ]
