# Generated by Django 4.2.11 on 2024-04-17 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_alter_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='room',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='webapp.room'),
        ),
    ]
