# Generated by Django 4.2.11 on 2024-04-20 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0009_alter_product_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('in_stock', 'В наличии'), ('for_order', 'Модерировано')], default='in_stock', max_length=20, verbose_name='Наличие'),
        ),
    ]
