# Generated by Django 4.2.11 on 2024-04-22 14:32

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0011_alter_product_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='room', chained_model_field='room', on_delete=django.db.models.deletion.CASCADE, related_name='products', to='webapp.category'),
        ),
    ]
