# Generated by Django 4.2.11 on 2024-05-29 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0018_order_comment_alter_basket_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='status',
        ),
    ]
