# Generated by Django 4.2.11 on 2024-06-01 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0026_alter_orderproduct_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='status',
            field=models.CharField(choices=[('pending', 'В пути'), ('in_stock', 'На складе'), ('delivered', 'Доставлено'), ('cancelled', 'Отменено')], default='in_stock', max_length=50, verbose_name='Статус'),
        ),
    ]
