# Generated by Django 4.2.11 on 2024-06-01 23:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0027_alter_delivery_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderproduct',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Итоговый прайс'),
        ),
    ]
